mysite/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    url(r'^', include('todo.urls')),
    url(r'^admin/', admin.site.urls),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

todo/urls.py
from django.conf.urls import url


from . import views

app_name = 'todo'
urlpatterns = [
	url(r'^$', views.first, name='first'),
	url(r'^Homepage/', views.index, name='index'),
	url(r'^Home/', views.home, name='home'),
	url(r'^Work/', views.work, name='work'),
	url(r'^Personal/', views.personal, name='personal'),
	url(r'^Travel/', views.travel, name='travel'),
	url(r'^Shopping/', views.shopping, name='shopping'),
	url(r'^Birthday/', views.birthday, name='birthday'),
	url(r'^Cooking/', views.cooking, name='cooking'),
	url(r'^7days/', views.days, name='7days'),
	url(r'^(?P<idt>[0-9]+)/', views.showDetails, name='details'),
	url(r'^update/(?P<idt>[0-9]+)/', views.updateView, name='update'),
	url(r'^delete/(?P<idt>[0-9]+)/', views.deleteView, name='delete'),
	url(r'^complete/(?P<idt>[0-9]+)/', views.completeTask, name='complete'),
	url(r'^signup/', views.signup, name='signup'),
	url(r'^user/(?P<idu>[0-9]+)/', views.showUser, name='showUser'),
	url(r'^editprofile/(?P<idu>[0-9]+)/', views.updateUser, name='updateUser'),
	url(r'^logout/', views.logout_user, name='logout'),
]

todo/models.py
from __future__ import unicode_literals
from django.contrib.auth.models import User
from datetime import datetime

from django.db import models

# Create your models here.

class Tasks(models.Model):
    name = models.CharField(max_length=50)
    date = models.DateField()
    category = models.CharField(max_length=20)
    completed = models.BooleanField(default=False)
    alarm = models.BooleanField(default=False)
    user = models.ForeignKey(User)

    def __str__(self):
        return self.name

class Home(models.Model):
    name = models.CharField(max_length=50)
    date = models.DateField()
    info = models.TextField(blank=True)
    alarm = models.BooleanField()
    task = models.ForeignKey(Tasks, on_delete=models.CASCADE)

    def __str__(self):
        return self.name

class Work(models.Model):
    name = models.CharField(max_length=50)
    date = models.DateField()
    info = models.TextField(blank=True)
    mails = models.EmailField(blank=True)
    workers = models.TextField(blank=True)
    alarm = models.BooleanField()
    task = models.ForeignKey(Tasks, on_delete=models.CASCADE)

    def __str__(self):
        return self.name

class Personal(models.Model):
    name = models.CharField(max_length=50)
    date = models.DateField()
    info = models.TextField(blank=True)
    alarm = models.BooleanField()
    task = models.ForeignKey(Tasks, on_delete=models.CASCADE)

    def __str__(self):
        return self.name

class Travel(models.Model):
    name = models.CharField(max_length=50, help_text=None)
    departure = models.DateField(help_text=None)
    arrival = models.DateField(help_text=None)
    destination = models.CharField(max_length=100)
    pack = models.TextField(blank=True)
    info = models.TextField(blank=True)
    alarm = models.BooleanField()
    task = models.ForeignKey(Tasks, on_delete=models.CASCADE)

    def __str__(self):
        return self.name



class Shopping(models.Model):
    name = models.CharField(max_length=50)
    date = models.DateField()
    stuff = models.TextField(blank=True)
    alarm = models.BooleanField()
    task = models.ForeignKey(Tasks, on_delete=models.CASCADE)

    def __str__(self):
        return self.name

class Birthday(models.Model):
    name = models.CharField(max_length=50)
    date = models.DateField()
    presents = models.TextField(blank=True)
    alarm = models.BooleanField()
    task = models.ForeignKey(Tasks, on_delete=models.CASCADE)

    def __str__(self):
        return self.name

class Cooking(models.Model):
    name = models.CharField(max_length=50)
    date = models.DateField()
    ingredients = models.TextField(blank=True)
    procedure = models.TextField(blank=True)
    alarm = models.BooleanField()
    task = models.ForeignKey(Tasks, on_delete=models.CASCADE)

    def __str__(self):
        return self.name

todo/forms.py
from django.forms import ModelForm, Textarea, widgets, PasswordInput
import html5.forms.widgets as html5_widgets
from .models import *
from django import forms

class formHome(ModelForm):
    class Meta:
        model = Home
        fields = ('name', 'date', 'info', 'alarm')
        widgets = {
            "date": html5_widgets.DateInput,
        }

class formWork(ModelForm):
    class Meta:
        model = Work
        fields = ('name', 'date', 'info', 'mails', 'workers', 'alarm')

        widgets = {
            "date": html5_widgets.DateInput,
            "info": Textarea(attrs={'rows': 4, 'cols':4}),
            "workers": Textarea(attrs={'rows': 4, 'cols': 4}),
        }


class formPersonal(ModelForm):
    class Meta:
        model = Personal
        fields = ('name', 'date', 'info', 'alarm')
        widgets = {
            "date": html5_widgets.DateInput,
        }

class formTravel(ModelForm):
    class Meta:
        model = Travel
        fields = ('name', 'departure', 'arrival', 'destination', 'pack', 'info', 'alarm')

        widgets = {
            "departure": html5_widgets.DateInput,
            "arrival": html5_widgets.DateInput,
            "pack": Textarea(attrs={'rows': 4, 'cols': 4}),
            "info": Textarea(attrs={'rows': 4, 'cols': 4}),
        }




class formShopping(ModelForm):
    class Meta:
        model = Shopping
        fields = ('name', 'date', 'stuff', 'alarm')
        widgets = {
            "date": html5_widgets.DateInput,
        }

class formBirthday(ModelForm):
    class Meta:
        model = Birthday
        fields = ('name', 'date', 'presents', 'alarm')
        widgets = {
            "date": html5_widgets.DateInput,
        }

class formCooking(ModelForm):
    class Meta:
        model = Cooking
        fields = ('name', 'date', 'ingredients', 'procedure', 'alarm')
        widgets = {
            "date": html5_widgets.DateInput,
            "ingredients": Textarea(attrs={'rows': 10, 'cols': 4}),
            "procedure": Textarea(attrs={'rows': 10, 'cols': 4}),
        }

class formLogin(forms.Form):
    username = forms.CharField(label='Username:', max_length=100)
    password = forms.CharField(label='Geslo:', max_length=100, widget=forms.PasswordInput)

class formSignup(forms.Form):
    first_name = forms.CharField(label="First name:", max_length=30)
    last_name = forms.CharField(label="Last name:", max_length=30)
    email = forms.EmailField()
    username = forms.CharField(label='Username:', max_length=100)
    password = forms.CharField(label='Geslo:', max_length=100, widget=forms.PasswordInput)

class formEditprofile(forms.Form):
    first_name = forms.CharField(label="First name:", max_length=30)
    last_name = forms.CharField(label="Last name:", max_length=30)
    email = forms.EmailField()
    username = forms.CharField(label='Username:', max_length=100)
    password = forms.CharField(label='Geslo:', max_length=100, widget=forms.PasswordInput, required=False)

todo/views.py
from django.contrib.auth.decorators import login_required
from django.db import transaction
from django.db.models import Q
from django.forms import model_to_dict
from django.http import HttpResponse
from django.http import HttpResponseRedirect
from django.shortcuts import render
from .forms import *
from django.contrib.auth import authenticate, login, logout
from django.urls import reverse
from datetime import timedelta


# Create your views here.

def first(request):
    context = {}
    context['forml'] = formLogin()
    if request.method == 'POST':
        forml = formLogin(request.POST)
        if forml.is_valid():
            user = authenticate(username=forml.cleaned_data['username'], password=forml.cleaned_data['password'])
            if user is not None:
                login(request, user)
                return HttpResponseRedirect('Homepage/')


    if request.user.is_authenticated:
        return HttpResponseRedirect('Homepage/')

    return render(request, 'todo/base.html', context)

@login_required(login_url='/')
def index(request):
    context = {}

    if request.method == 'POST':
        if 'addhome' in request.POST:
            formh = formHome(request.POST)
            if formh.is_valid():
                t = Tasks(name=formh.cleaned_data['name'], date=formh.cleaned_data['date'],
                          category="Home", completed=False, user=request.user,
                          alarm=formh.cleaned_data['alarm'])
                t.save()

                h = Home(name=formh.cleaned_data['name'], date=formh.cleaned_data['date'],
                         info=formh.cleaned_data['info'], alarm=formh.cleaned_data['alarm'],
                         task=t)
                h.save()

        elif 'addwork' in request.POST:
            formw = formWork(request.POST)
            if formw.is_valid():
                t = Tasks(name=formw.cleaned_data['name'], date=formw.cleaned_data['date'],
                          category="Work", completed=False, user=request.user,
                          alarm=formw.cleaned_data['alarm'])
                t.save()

                w = Work(name=formw.cleaned_data['name'], date=formw.cleaned_data['date'],
                         info=formw.cleaned_data['info'], mails=formw.cleaned_data['mails'],
                         workers=formw.cleaned_data['workers'], alarm=formw.cleaned_data['alarm'],
                         task=t)
                w.save()
        elif 'addpersonal' in request.POST:
            formp = formPersonal(request.POST)
            if formp.is_valid():
                t = Tasks(name=formp.cleaned_data['name'], date=formp.cleaned_data['date'],
                          category="Personal", completed=False, user=request.user,
                          alarm=formp.cleaned_data['alarm'])
                t.save()

                p = Personal(name=formp.cleaned_data['name'], date=formp.cleaned_data['date'],
                         info=formp.cleaned_data['info'], alarm=formp.cleaned_data['alarm'],
                         task=t)
                p.save()

        elif 'addtravel' in request.POST:
            formt = formTravel(request.POST or None)
            if formt.is_valid():
                t = Tasks(name=formt.cleaned_data['name'], date=formt.cleaned_data['departure'],
                          category="Travel", completed=False, user=request.user,
                          alarm=formt.cleaned_data['alarm'])
                t.save()

                tr = Travel(name=formt.cleaned_data['name'], arrival=formt.cleaned_data['arrival'],
                            departure=formt.cleaned_data['departure'], destination=formt.cleaned_data['destination'],
                            pack=formt.cleaned_data['pack'], info=formt.cleaned_data['info'],
                            alarm=formt.cleaned_data['alarm'],
                            task=t)
                tr.save()
            else:
                return HttpResponse("Drek")
        elif 'addshopping' in request.POST:
            forms = formShopping(request.POST)
            if forms.is_valid():
                t = Tasks(name=forms.cleaned_data['name'], date=forms.cleaned_data['date'],
                          category="Shopping", completed=False, user=request.user,
                          alarm=forms.cleaned_data['alarm'])
                t.save()

                s = Shopping(name=forms.cleaned_data['name'], date=forms.cleaned_data['date'],
                         stuff=forms.cleaned_data['stuff'], alarm=forms.cleaned_data['alarm'],
                         task=t)
                s.save()
        elif 'addbirthday' in request.POST:
            formb = formBirthday(request.POST)
            if formb.is_valid():
                t = Tasks(name=formb.cleaned_data['name'], date=formb.cleaned_data['date'],
                          category="Birthday", completed=False, user=request.user,
                          alarm=formb.cleaned_data['alarm'])
                t.save()

                b = Birthday(name=formb.cleaned_data['name'], date=formb.cleaned_data['date'],
                            presents=formb.cleaned_data['presents'], alarm=formb.cleaned_data['alarm'],
                            task=t)
                b.save()
        elif 'addcooking' in request.POST:
            formc = formCooking(request.POST)
            if formc.is_valid():
                t = Tasks(name=formc.cleaned_data['name'], date=formc.cleaned_data['date'],
                          category="Cooking", completed=False, user=request.user,
                          alarm=formc.cleaned_data['alarm'])
                t.save()

                c = Cooking(name=formc.cleaned_data['name'], date=formc.cleaned_data['date'],
                            ingredients=formc.cleaned_data['ingredients'], procedure=formc.cleaned_data['procedure'],
                            alarm=formc.cleaned_data['alarm'],
                            task=t)
                c.save()

    formh = formHome()
    formw = formWork()
    formp = formPersonal()
    formt = formTravel()
    forms = formShopping()
    formb = formBirthday()
    formc = formCooking()

    transaction.commit()
    tasks = Tasks.objects.filter(user=request.user, date=datetime.now().date())
    how_many_days = 30
    min=datetime.today()-timedelta(days=1)
    past = Tasks.objects.filter(user=request.user,
                                date__gte=datetime.today()-timedelta(days=how_many_days),
                                completed=False).exclude(date__gte=datetime.today())

    future = Tasks.objects.filter(user=request.user, date__lte=datetime.today()+timedelta(days=how_many_days), alarm=True,
                                  completed=False)


    context = {'formh': formh, 'formw': formw, 'formp': formp, 'formt': formt, 'forms': forms, 'formb': formb,
             'formc': formc, 'tasks_today': tasks, 'past': past, 'future': future}

    return render(request, 'todo/index.html', context)

@login_required(login_url='/')
def home(request):
    context = {}

    transaction.commit()
    context['tasks_progress'] = Tasks.objects.filter(user=request.user, category="Home", completed=False)
    context['tasks_completed'] = Tasks.objects.filter(user=request.user, category="Home", completed=True)

    how_many_days = 30
    context['past'] = Tasks.objects.filter(user=request.user, date__gte=datetime.now() - timedelta(days=how_many_days),
                                           completed=False).exclude(date__gte=datetime.today())
    context['future'] = Tasks.objects.filter(user=request.user, date__lte=datetime.now() + timedelta(days=how_many_days),
                                  alarm=True, completed=False)

    return render(request, 'todo/details.html', context)

@login_required(login_url='/')
def work(request):
    context = {}


    context['tasks_progress'] = Tasks.objects.filter(user=request.user, category="Work", completed=False)
    context['tasks_completed'] = Tasks.objects.filter(user=request.user, category="Work", completed=True)

    how_many_days = 30
    context['past'] = Tasks.objects.filter(user=request.user, date__gte=datetime.now() - timedelta(days=how_many_days),
                                           completed=False).exclude(date__gte=datetime.today())
    context['future'] = Tasks.objects.filter(user=request.user,
                                             date__lte=datetime.now() + timedelta(days=how_many_days),
                                             alarm=True, completed=False)
    return render(request, 'todo/details.html', context)

@login_required(login_url='/')
def personal(request):
    context = {}


    context['tasks_progress'] = Tasks.objects.filter(user=request.user, category="Personal", completed=False)
    context['tasks_completed'] = Tasks.objects.filter(user=request.user, category="Personal", completed=True)

    how_many_days = 30
    context['past'] = Tasks.objects.filter(user=request.user, date__gte=datetime.now() - timedelta(days=how_many_days),
                                           completed=False).exclude(date__gte=datetime.today())
    context['future'] = Tasks.objects.filter(user=request.user,
                                             date__lte=datetime.now() + timedelta(days=how_many_days),
                                             alarm=True, completed=False)

    return render(request, 'todo/details.html', context)

@login_required(login_url='/')
def travel(request):
    context = {}


    context['tasks_progress'] = Tasks.objects.filter(user=request.user, category="Travel", completed=False)
    context['tasks_completed'] = Tasks.objects.filter(user=request.user, category="Travel", completed=True)

    how_many_days = 30
    context['past'] = Tasks.objects.filter(user=request.user, date__gte=datetime.now() - timedelta(days=how_many_days),
                                           completed=False).exclude(date__gte=datetime.today())

todo/templates/todo/7days.html
{% extends 'todo/base.html' %}

{% block main %}
    <div id="dayslists">
        <div id="first">
            <div id="dayone"></div>
            <div id="textone">
                <a href="focus1" onclick="return focus1(this)"><h2> Tomorrow:</h2></a>
                <ul>
                    <li>
                        {% for task in day1 %}
                        <form method="POST" action="{% url 'todo:complete' task.id %}">
                            {% csrf_token %}
                            <input type="checkbox" name="compl" value="{{ task.name }}" onchange="submit()"
                            {% if task.completed == True %}checked {% endif %}>
                        </form>
                            <a href="{% url 'todo:details' task.id %}" >{{ task.name }}</a>
                        {% endfor %}
                    </li>
                </ul>
            </div>
            <div id="daytwo"></div>
            <div id="texttwo">
                <a href="focus2" onclick="return focus2(this)"><h2> In 2 days:</h2></a>
                <ul>
                    <li>
                        {% for task in day2 %}
                        <form method="POST" action="{% url 'todo:complete' task.id %}">
                            {% csrf_token %}
                            <input type="checkbox" name="compl" value="{{ task.name }}" onchange="submit()"
                            {% if task.completed == True %}checked {% endif %}>
                        </form>
                            <a href="{% url 'todo:details' task.id %}" >{{ task.name }}</a>
                        {% endfor %}
                    </li>
                </ul>
            </div>
            <div id="daythree"></div>
            <div id="textthree">
                <a href="focus3" onclick="return focus3(this)"><h2> In 3 days:</h2></a>
                <ul>
                    <li>
                        {% for task in day3 %}
                        <form method="POST" action="{% url 'todo:complete' task.id %}">
                            {% csrf_token %}
                            <input type="checkbox" name="compl" value="{{ task.name }}" onchange="submit()"
                            {% if task.completed == True %}checked {% endif %}>
                        </form>
                            <a href="{% url 'todo:details' task.id %}" >{{ task.name }}</a>
                        {% endfor %}
                    </li>
                </ul>
            </div>
            <div id="dayfour"></div>
            <div id="textfour">
                <a href="focus4" onclick="return focus4(this)"><h2> In 4 days:</h2></a>
                <ul>
                    <li>
                        {% for task in day4 %}
                        <form method="POST" action="{% url 'todo:complete' task.id %}">
                            {% csrf_token %}
                            <input type="checkbox" name="compl" value="{{ task.name }}" onchange="submit()"
                            {% if task.completed == True %}checked {% endif %}>
                        </form>
                            <a href="{% url 'todo:details' task.id %}" >{{ task.name }}</a>
                        {% endfor %}
                    </li>
                </ul>
            </div>
        </div>
        <div id="second">
            <div id="dayfive"></div>
            <div id="textfive">
                <a href="focus5" onclick="return focus5(this)"><h2> In 5 days:</h2></a>
                <ul>
                    <li>
                        {% for task in day5 %}
                        <form method="POST" action="{% url 'todo:complete' task.id %}">
                            {% csrf_token %}
                            <input type="checkbox" name="compl" value="{{ task.name }}" onchange="submit()"
                            {% if task.completed == True %}checked {% endif %}>
                        </form>
                            <a href="{% url 'todo:details' task.id %}" >{{ task.name }}</a>
                        {% endfor %}
                    </li>
                </ul>
            </div>
            <div id="daysix"></div>
            <div id="textsix">
                <a href="focus6" onclick="return focus6(this)"><h2> In 6 days:</h2></a>
                <ul>
                    <li>
                        {% for task in day6 %}
                        <form method="POST" action="{% url 'todo:complete' task.id %}">
                            {% csrf_token %}
                            <input type="checkbox" name="compl" value="{{ task.name }}" onchange="submit()"
                            {% if task.completed == True %}checked {% endif %}>
                        </form>
                            <a href="{% url 'todo:details' task.id %}" >{{ task.name }}</a>
                        {% endfor %}
                    </li>
                </ul>
            </div>
            <div id="dayseven"></div>
            <div id="textseven">
                <a href="focus7" onclick="return focus7(this)"><h2> In 7 days:</h2></a>
                <ul>
                    <li>
                        {% for task in day7 %}
                        <form method="POST" action="{% url 'todo:complete' task.id %}">
                            {% csrf_token %}
                            <input type="checkbox" name="compl" value="{{ task.name }}" onchange="submit()"
                            {% if task.completed == True %}checked {% endif %}>
                        </form>
                            <a href="{% url 'todo:details' task.id %}" >{{ task.name }}</a>
                        {% endfor %}
                    </li>
                </ul>
            </div>
        </div>
    </div>

    <div id="dim"></div>
    <div id="focus1">
        <button type="button" onclick="hidefocus1()">Close</button>
        <h1>Tomorrow:</h1>
        <ul>
            <li>
                {% for task in day1 %}
                <form method="POST" action="{% url 'todo:complete' task.id %}">
                    {% csrf_token %}
                    <input type="checkbox" name="compl" value="{{ task.name }}" onchange="submit()"
                    {% if task.completed == True %}checked {% endif %}>
                </form>
                    <a href="{% url 'todo:details' task.id %}" >{{ task.name }}</a>
                {% endfor %}
            </li>
        </ul>
    </div>

    <div id="focus2">
        <button type="button" onclick="hidefocus2()">Close</button>
        <h1>In 2 days:</h1>
        <ul>
            <li>
                {% for task in day2 %}
                <form method="POST" action="{% url 'todo:complete' task.id %}">
                    {% csrf_token %}
                    <input type="checkbox" name="compl" value="{{ task.name }}" onchange="submit()"
                    {% if task.completed == True %}checked {% endif %}>
                </form>
                    <a href="{% url 'todo:details' task.id %}" >{{ task.name }}</a>
                {% endfor %}
            </li>
        </ul>
    </div>

    <div id="focus3">
        <button type="button" onclick="hidefocus3()">Close</button>
        <h1>In 3 days:</h1>
        <ul>
            <li>
                {% for task in day3 %}
                <form method="POST" action="{% url 'todo:complete' task.id %}">
                    {% csrf_token %}
                    <input type="checkbox" name="compl" value="{{ task.name }}" onchange="submit()"
                    {% if task.completed == True %}checked {% endif %}>
                </form>
                    <a href="{% url 'todo:details' task.id %}" >{{ task.name }}</a>
                {% endfor %}
            </li>
        </ul>
    </div>

    <div id="focus4">
        <button type="button" onclick="hidefocus4()">Close</button>
        <h1>In 4 days:</h1>
        <ul>
            <li>
                {% for task in day4 %}
                <form method="POST" action="{% url 'todo:complete' task.id %}">
                    {% csrf_token %}
                    <input type="checkbox" name="compl" value="{{ task.name }}" onchange="submit()"
                    {% if task.completed == True %}checked {% endif %}>
                </form>
                    <a href="{% url 'todo:details' task.id %}" >{{ task.name }}</a>
                {% endfor %}
            </li>
        </ul>
    </div>

    <div id="focus5">
        <button type="button" onclick="hidefocus5()">Close</button>
        <h1>In 5 days:</h1>
        <ul>
            <li>
                {% for task in day5 %}
                <form method="POST" action="{% url 'todo:complete' task.id %}">
                    {% csrf_token %}
                    <input type="checkbox" name="compl" value="{{ task.name }}" onchange="submit()"
                    {% if task.completed == True %}checked {% endif %}>
                </form>
                    <a href="{% url 'todo:details' task.id %}" >{{ task.name }}</a>
                {% endfor %}
            </li>
        </ul>
    </div>

    <div id="focus6">
        <button type="button" onclick="hidefocus6()">Close</button>
        <h1>In 6 days:</h1>
        <ul>
            <li>
                {% for task in day6 %}
                <form method="POST" action="{% url 'todo:complete' task.id %}">
                    {% csrf_token %}
                    <input type="checkbox" name="compl" value="{{ task.name }}" onchange="submit()"
                    {% if task.completed == True %}checked {% endif %}>
                </form>
                    <a href="{% url 'todo:details' task.id %}" >{{ task.name }}</a>
                {% endfor %}
            </li>
        </ul>
    </div>

    <div id="focus7">
        <button type="button" onclick="hidefocus7()">Close</button>
        <h1>In 7 days:</h1>
        <ul>
            <li>
                {% for task in day7 %}
                <form method="POST" action="{% url 'todo:complete' task.id %}">
                    {% csrf_token %}
                    <input type="checkbox" name="compl" value="{{ task.name }}" onchange="submit()"
                    {% if task.completed == True %}checked {% endif %}>
                </form>
                    <a href="{% url 'todo:details' task.id %}" >{{ task.name }}</a>
                {% endfor %}
            </li>
        </ul>
    </div>
{% endblock %}

todo/templates/todo/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <title>TO-DO</title>
    <link rel="stylesheet" href="{% static 'todo/style.css' %}">
    <script src="{% static 'todo/functions.js' %}"></script>

</head>
<body>
    {% if user.is_authenticated %}
        <div id="band">
            <a href="/Homepage/"><img src="{% static 'todo/images/logo2_2.png' %}" alt="logo" /></a>
            <div id="menu">
                <ul>
                    <li><a href="Notifications" onclick="return showNotifications(this)"><img src="{% static 'todo/images/alarm.png' %}" alt="logo" /></a> </li>
                    <!--<li><a href="#" "><img src="{% static 'todo/images/calendar.png' %}" alt="logo" /></a> </li>-->
                    <li><a href="User" onclick="return showUser(this)"><img src="{% static 'todo/images/user.png' %}" alt="logo" /></a> </li>
                </ul>
            </div>
        </div>
        <div id="sidemenuband">
        <div id="sidemenu">
            <ul>
                <li><a href="{% url 'todo:index'%}">Today</a></li>
                <li><a href="{% url 'todo:7days'%}">Next 7 days</a> </li>
                <li><a href="">  </a></li>
                <li><a href="{% url 'todo:home'%}">Home </a></li>
                <li><a href="{% url 'todo:work'%}">Work</a> </li>
                <li><a href="{% url 'todo:personal'%}">Personal</a> </li>
                <li><a href="{% url 'todo:travel'%}">Travel</a> </li>
                <li><a href="{% url 'todo:shopping'%}">Shopping</a> </li>
                <li><a href="{% url 'todo:birthday'%}">Birthday</a> </li>
                <li><a href="{% url 'todo:cooking'%}">Cooking</a> </li>
            </ul>
        </div>
        </div>
        <section class="">
            {% block main %}
            {% endblock %}
        </section>
    {% else %}
        <div id="band">
            <a href=""><img src="{% static 'todo/images/logo2_2.png' %}" alt="logo" /></a>

            <div id="sign">
                <ul>
                    <li><a href="/signup/">SIGN UP</a></li>
                    <li><a href="#" onclick="return showlogin(this)">LOG IN</a></li>
                </ul>
            </div>
        </div>
        <section class="">
            {% block sign %}
            {% endblock %}
        </section>
    {% endif %}

    <div id="userlist"></div>
    <div id="user">
        <label>{{ user.first_name }} {{ user.last_name }}</label><br>
        <form action="/user/{{ user.id }}" >
            <button id="buttoneditprofile" type="submit"  >Edit profile</button><br>
        </form>

        <form action="{% url 'todo:logout' %}" >
            <button id="logout" type="submit" name="logout">Log out</button>
        </form>

    </div>

    <div id="notifications">
        <h2>Notifications:</h2>
        {% for p in past %}
            <p><img src="{% static 'todo/images/clock.png' %}" alt="clock">
                <b><i>Unfinished:</i></b> {{ p.name }} from {{ p.date }}, category: {{ p.category }}
            </p>
        {% endfor %}
        {% for f in future %}
            <p><img src="{% static 'todo/images/clock.png' %}" alt="clock">
                <b>Alarm:</b> {{ f.name }} till {{ f.date }}, category: {{ f.category }}
            </p>
        {% endfor %}
    </div>

    <div id="loginlist"></div>
    <div id="login">
        <form method='POST' action="{% url 'todo:first' %}" name="login" class="lform">
            {% csrf_token %}
            {{ forml.as_p }}
            <button type="submit" name="login" >Log in</button>
        </form>
    </div>
</body>
</html>

todo/templates/todo/editprofile.html
{% extends 'todo/base.html' %}

{% block main %}
    <div id="formsignuplist"></div>
    <div id="formsignup">
        <h1>UPDATE PROFILE:</h1>
        <form method="post" action="{% url 'todo:updateUser' user.id%}">
            {% csrf_token %}
            {{ form.as_p }}
            <button type="submit" name="editp">Update</button>
        </form>
    </div>
{% endblock %}